# Generated by Django 2.0.6 on 2021-09-05 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='barberia',
            fields=[
                ('pk_barberia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cita',
            fields=[
                ('pk_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=20)),
                ('fk_barberia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.barberia')),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('pk_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=60)),
                ('c_cita', models.CharField(max_length=70)),
                ('fk_barberia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.barberia')),
            ],
        ),
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('pk_empleados', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.IntegerField()),
                ('Sexo', models.CharField(max_length=15)),
                ('fk_barberia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.barberia')),
            ],
        ),
        migrations.CreateModel(
            name='servicios',
            fields=[
                ('pk_servicios', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descuento', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='fk_servicios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.servicios'),
        ),
        migrations.AddField(
            model_name='cita',
            name='fk_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.cliente'),
        ),
    ]
