# Generated by Django 2.0.6 on 2021-09-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barberia',
            options={'ordering': ['nombre'], 'verbose_name': 'barberia', 'verbose_name_plural': 'barberias'},
        ),
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['fecha'], 'verbose_name': 'cita', 'verbose_name_plural': 'citas'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre'], 'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='empleados',
            options={'ordering': ['nombre'], 'verbose_name': 'empleados', 'verbose_name_plural': 'empleadoss'},
        ),
        migrations.AlterModelOptions(
            name='servicios',
            options={'ordering': ['tipo'], 'verbose_name': 'servicios', 'verbose_name_plural': 'servicioss'},
        ),
        migrations.AddField(
            model_name='servicios',
            name='imagenes',
            field=models.URLField(default='https://ca-times.brightspotcdn.com/dims4/default/87be6da/2147483647/strip/true/crop/1970x1108+39+0/resize/1200x675!/quality/90/?url=https%3A%2F%2Fcalifornia-times-brightspot.s3.amazonaws.com%2F12%2Fa5%2F79e097ccf62312d18a025f22ce48%2Fhoyla-recuento-11-cosas-aman-gatos-top-001', max_length=8000),
        ),
    ]
